#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1073398446                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Your college sports recruiting news

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Bryan Bartow                                
your_link                                 : https://bryanbartow.com                     
your_city                                 : Austin                                
email_address                             : bryan@obmonitor.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : bryanbartow
github_username                           : bryanbartow
youtube_username                          :
mastodon_link                             : https://mastodon.social/@bryanbartow



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Your Personalized Feed
    description                           : We only show you the threads you care about.
    fontawesome_icon_name                 : user-check
    
  - title                                 : Never Miss a Thing
    description                           : Customizable push notifications ensure you never miss out on breaking news.
    fontawesome_icon_name                 : bell

  - title                                 : Keywords
    description                           : Use keywords to get notified anyone posts about your favorite subject.
    fontawesome_icon_name                 : magnifying-glass

  - title                                 : Favorite Users
    description                           : Follow your favorite users and get notified any time they post.
    fontawesome_icon_name                 : user-plus

  - title                                 : Topics (beta)
    description                           : Browse all of your threads organized by topic
    fontawesome_icon_name                 : comments
  
  - title                                 : Bookmarks
    description                           : Bookmark threads for later reference.
    fontawesome_icon_name                 : bookmark

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#c16a30"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#c16a30"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#c16a30"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#c16a30"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
